from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional


class StepMetrics(BaseModel):
    """Metrics for a single agent step.

    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required for evaluation, empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(..., description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(..., description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(..., description="Wall-clock time for the LLM API call in milliseconds")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(),
                           description="ISO 8601 timestamp of when this step was recorded")
    api_url: str = Field(default="", description="Base URL of the LLM APIendpoint (e.g., 'https://openrouter.ai/api/v1')")
    model_name: str = Field(default="", description="Model identifier used for this step (e.g., 'qwen/qwen3-235b-a22b-2507')")
    llm_output: str = Field(default="", description="Raw text generated by the LLM before code extraction")
    sandbox_input: str = Field(default="", description="Python code sent to the sandbox for execution")
    sandbox_output: str = Field(default="", description="Sandbox execution result (stdout/stderr/error message)")
    retries: int = Field(default=0, description="Number of LLM API retries before getting a successful response "
                         "(0 = first attempt succeeded)")


class SolutionOutput(BaseModel):
    """Output from student solution, required format for evaluation.

    This is the JSON structure your agent must produce and write to solution.
    json.
    The moulinette validates this against task correctness and metrics limits.
    """
    task_id: str = Field(..., description="Task identifier (MBPP task_id as string, or SWE-bench instance_id)")
    benchmark: str = Field(..., description="Benchmark type: 'mbpp' or 'swebench'")
    success: bool = Field(..., description="Whether the agent believes it solved the task")
    solution: str = Field(..., description="For MBPP: the Python function code. For SWE-bench: the git patch (diff)")
    iterations: int = Field(..., description="Number of agent loop iterations used")
    total_requests: int = Field(..., description="Total number of LLM API requests made (including retries)")
    total_input_tokens: int = Field(..., description="Sum of input_tokens across all steps")
    total_output_tokens: int = Field(..., description="Sum of output_tokens across all steps")
    total_time_seconds: float = Field(..., description="Wall-clock time from agent start to finish")
    steps: list[StepMetrics] = Field(default_factory=list, description="Perstep metrics, one entry per agent iteration")
    system_prompt: str = Field(default="", description="Full system prompt sent to the LLM (for provenance checking)")
    error: Optional[str] = Field(default=None, description="Error message if the agent failed (None if successful)")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(),
                           description="ISO 8601 timestamp of when the solution was produced")


# class StepMetrics(BaseModel):
#     """1回のエージェントステップにおけるメトリクス（指標）。

#     各ステップは、LLMの生成からサンドボックスの実行までの1サイクルに相当する。
#     評価のためにすべてのフィールドが必須となるが、該当しないフィールド（例：サンドボックスの実行がない場合など）には空文字を許容する。
#     """
#     step: int = Field(..., description="1から始まるイテレーション（反復）番号")
#     input_tokens: int = Field(..., description="このステップでLLMに送信されたトークン数")
#     output_tokens: int = Field(..., description="このステップでLLMによって生成されたトークン数")
#     request_time_ms: float = Field(..., description="LLM API呼び出しにかかった実時間（ミリ秒）")
#     timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(),
#                            description="このステップが記録された日時のISO 8601タイムスタンプ")
#     api_url: str = Field(default="", description="LLM APIエンドポイントのベースURL（例: 'https://openrouter.ai/api/v1'）")
#     model_name: str = Field(default="", description="このステップで使用されたモデルの識別子（例: 'qwen/qwen3-235b-a22b-2507'）")
#     llm_output: str = Field(default="", description="コード抽出前にLLMが生成した生のテキスト")
#     sandbox_input: str = Field(default="", description="実行のためにサンドボックスに送信されたPythonコード")
#     sandbox_output: str = Field(default="", description="サンドボックスの実行結果（標準出力/標準エラー/エラーメッセージ）")
#     retries: int = Field(default=0, description="成功したレスポンスを得るまでのLLM APIの再試行回数（0 = 初回で成功）")


# class SolutionOutput(BaseModel):
#     """学生のソリューションからの出力であり、評価に必要なフォーマット。

#     これはエージェントが生成し、solution.jsonに書き込む必要があるJSON構造である。
#     moulinetteはこれを用いて、タスクの正解性とメトリクスの制限を検証する。
#     """
#     task_id: str = Field(..., description="タスク識別子（文字列としてのMBPPのtask_id、またはSWE-benchのinstance_id）")
#     benchmark: str = Field(..., description="ベンチマークの種類: 'mbpp' または 'swebench'")
#     success: bool = Field(..., description="エージェントがタスクを解決したと判断したかどうか")
#     solution: str = Field(..., description="MBPPの場合: Pythonの関数コード。SWE-benchの場合: gitパッチ（diff）")
#     iterations: int = Field(..., description="使用したエージェントループのイテレーション数")
#     total_requests: int = Field(..., description="行われたLLM APIリクエストの総数（再試行を含む）")
#     total_input_tokens: int = Field(..., description="すべてのステップにおけるinput_tokensの合計")
#     total_output_tokens: int = Field(..., description="すべてのステップにおけるoutput_tokensの合計")
#     total_time_seconds: float = Field(..., description="エージェントの開始から終了までの実時間（秒）")
#     steps: list[StepMetrics] = Field(default_factory=list, description="ステップごとのメトリクス。エージェントのイテレーションごとに1つのエントリ")
#     system_prompt: str = Field(default="", description="LLMに送信された完全なシステムプロンプト（出所確認用）")
#     error: Optional[str] = Field(default=None, description="エージェントが失敗した場合のエラーメッセージ（成功した場合はNone）")
#     timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(),
#                            description="ソリューションが生成された日時のISO 8601タイムスタンプ")
