from typing import Protocol

from src.mcp_core.models import jsonrpc as rpc


class ClientTransport(Protocol):
    def open(self) -> None: ...
    def send(self, message: rpc.JSONRPCMessage) -> None: ...
    def receive(self) -> rpc.JSONRPCMessage: ...
    def set_protocol_version(self, version: str) -> None: ...
    def close(self) -> None: ...
